### PR TITLE
Release 2021-10-13

### PR DESCRIPTION
**Pull request by LoneRifle**
This release contains the following major changes:
- #405 
  - #549 
- #554 
  - #567 
- #556 
- #568

It also contains the following:
- #543 
- #557 
- #558 
- #560 
- #566

### CODE REVIEW

**Review by LinHuiqing — CHANGES_REQUESTED** [review]
LinkDecorator is throwing an error for some questions D: 
https://staging.ask.gov.sg/questions/407

Would it be possible to take a look at the content in this post? @LoneRifle

**Comment by LoneRifle** [comment]
> LinkDecorator is throwing an error for some questions D: https://staging.ask.gov.sg/questions/407
> 
> Would it be possible to take a look at the content in this post? @LoneRifle

Content is an invalid URL - might have been a longstanding problem:
```
agencyLogo: "https://logos.ask.gov.sg/ipos-logo.png"
body: "<p>Q<a href=\"Hi\" target=\"_blank\">uestion</a>&nbsp;</p>\n<p></p>\n<p>aaaGive your question a short and relevant title</p>\n"
createdAt: "2021-08-02T03:25:25.000Z"
```
the above causes the following:
```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at component (LinkDecorator.tsx:37)
```

**Comment by LinHuiqing** [comment]
Ah so we just assume its unrelated to the changes made for this release? Anyways looks good to me otherwise.

**Review by wanlingt — APPROVED** [review]
lgtm

**Review by LinHuiqing — APPROVED** [review]

**Pull request merged**
