### PR TITLE
chore: move testing dependencies to devDependencies

### PR DESCRIPTION
**Pull request by zxt-tzx**
minor housekeeping: move testing dependencies to devDependencies

### CODE REVIEW

**Comment by christopherlim98** [comment]
LGTM, maybe we can update the package-lock too? 

(Strange it was in dependencies instead of devDependenices!)

**Review by christopherlim98 — APPROVED** [review]
LGTM, maybe we can update the package-lock too using `npm ci` in this commit.

(Strange it was in dependencies instead of devDependenices!)

**Comment by zxt-tzx** [comment]
> update the package-lock

Done!

**Comment by christopherlim98** [comment]
@tan-zx look good, merge when ready !

**Pull request merged**
