### PR TITLE
refactor(officer-dashboard): merge with QuestionsList

### LINKED ISSUE #536: Adjust margins of questions list in HomePage for logged in users
**Describe the bug**
When a user is logged in, the margins of questions list in the landing page are larger compared to the non-logged in view

**To Reproduce**
1. Login
2. Scroll through the questions on the main page
3. Compare margins against view of non logged-in users

**Expected behavior**
Margins of questions list should have consistent alignment across logged in and non logged in users, according to the designs on Figma

**Screenshots**
Logged in view:
image

### PR DESCRIPTION
**Pull request by LoneRifle**
## Problem

The codebase contains a duplicate set of components for officers and members of the public, 
which can be merged together for now. QuestionsList risks bloating from taking on extra logic
to determine which posts to fetch, in addition to allowing footer component overrides, but 
given that there are only two non-trivial parts of the component that are configurable,
this is not so much of a concern for now.

Fixes #536 

## Solution

Apply DRY and collapse OfficerDashboard and its children into
QuestionsList, given their near-identical implementations, with the
distinct UI feature - the edit button - being implemented on PostItem.

- Type the response returned by `PostService.listAnswerablePosts()`
- Add boolean prop to QuestionsList, influencing which endpoint to call
  when retrieving posts. When true, retrieve posts that are answerable
- Get HomePage to just use the QuestionsList, ensuring that the 50-row
  page size for public officers is maintained
- Remove AnswerableQuestions and OfficerDashboard, no longer used

## Screenshots
| Before | After |
|---|---|
| image | image |

## Tests

- Ensure that an officer can continue to edit questions

### CODE REVIEW

**Comment by LinHuiqing** [comment]
Should the post items for officer dashboard still be centered vertically? (it currently isn't)

**Review by LinHuiqing — APPROVED** [review]
lgtm

**Review by wanlingt — APPROVED** [review]
lgtm!

Feel like the screens for the officer view can be rejigged since the number of questions listed is a standard 50 (as opposed to clicking view all -> actually viewing more questions) but that's probably a separate issue for the not so near future?

**Comment by LoneRifle** [comment]
> Feel like the screens for the officer view can be rejigged since the number of questions listed is a standard 50 (as opposed to clicking view all -> actually viewing more questions) but that's probably a separate issue for the not so near future?

I'm not so worried about that for two reasons:
- the officer would probably want to see as many questions as possible since he's doing content moderation, not looking for answers, and;
- more than likely, the officer would be viewing the page on his/her desktop

**Comment by wanlingt** [comment]
> > Feel like the screens for the officer view can be rejigged since the number of questions listed is a standard 50 (as opposed to clicking view all -> actually viewing more questions) but that's probably a separate issue for the not so near future?
> 
> I'm not so worried about that for two reasons:
> 
> * the officer would probably want to see as many questions as possible since he's doing content moderation, not looking for answers, and;
> * more than likely, the officer would be viewing the page on his/her desktop

yeah agree, was mainly referring to the officer having to scroll through 50 questions again after they click "View all questions", instead of being able to proceed to the next 50 questions immediately

**Comment by LoneRifle** [comment]
Holding off on this PR until after release on Weds

**Comment by LoneRifle** [comment]
> > > Feel like the screens for the officer view can be rejigged since the number of questions listed is a standard 50 (as opposed to clicking view all -> actually viewing more questions) but that's probably a separate issue for the not so near future?
> > 
> > 
> > I'm not so worried about that for two reasons:
> > 
> > * the officer would probably want to see as many questions as possible since he's doing content moderation, not looking for answers, and;
> > * more than likely, the officer would be viewing the page on his/her desktop
> 
> yeah agree, was mainly referring to the officer having to scroll through 50 questions again after they click "View all questions", instead of being able to proceed to the next 50 questions immediately

~I believe View all questions is only shown for members of the public =)~ Nope sorry I was wrong I'm an idiot.

**Pull request merged**
