### PR TITLE
Release 2021-10-11

### PR DESCRIPTION
**Pull request by LoneRifle**
This release contains the following:

- #513
- #514 
- #515
- #516 
- #519
  - #534 
  - #535 
  - #537
- #521

### CODE REVIEW

**Review by LinHuiqing — CHANGES_REQUESTED** [review]
Main page and agency main page still has 50 questions and does not have "View all questions" button.

**Comment by LoneRifle** [comment]
> Main page and agency main page still has 50 questions and does not have "View all questions" button.

image
 
Could you double check?

**Comment by wanlingt** [comment]
> Main page and agency main page still has 50 questions and does not have "View all questions" button.

I see it though.. (both the button and the 10 questions)
image

**Comment by LinHuiqing** [comment]
Hm for some reason my site is still the old one though I disabled caching on the network panel :x shows up on incognito, so should be fine ps

**Comment by LinHuiqing** [comment]
https://staging.ask.gov.sg/agency/ema?tags=
Screenshot 2021-10-11 at 9 21 23 AM

On this page, there should be 30 questions per page right? It seems to only have 10 questions per page for me?

**Review by wanlingt — CHANGES_REQUESTED** [review]
Questions don't seem to be filtered by agency on agency-specific pages

image

**Comment by LinHuiqing** [comment]
> * feat(view-all): add 'View all questions' button on main (and agency) pages #514

Also, should this be the PR referenced? Wasn't this reverted?

**Comment by wanlingt** [comment]
> > * feat(view-all): add 'View all questions' button on main (and agency) pages [feat(view-all): add 'View all questions' button on main (and agency) pages #514](https://github.com/opengovsg/askgovsg/pull/514)
> 
> Also, should this be the PR referenced? Wasn't this reverted?

if i recall correctly, it was un-reverted during the git surgery

**Comment by wanlingt** [comment]
logged in user:
image
the margins of questions list increase when a user is logged in

**Comment by LoneRifle** [comment]
> logged in user: image the margins of questions list increase when a user is logged in

Let's not worry about logged in users for now.

**Comment by LinHuiqing** [comment]
Some questions are missing when questions are not filtered by tag. Look out for questions "question 1 question 1 ... question 1" and "question 2 question 2 ... question 2"

https://user-images.githubusercontent.com/37061143/136722855-eeff07b4-242d-4683-91e5-efe1fff23e35.mov

**Review by wanlingt — APPROVED** [review]
lgtm

**Comment by LoneRifle** [comment]
image
Multi-line topics should remain left-aligned

**Comment by LinHuiqing** [comment]
Multiline topics should not overflow when selected :/

Screenshot 2021-10-11 at 10 43 00 AM

**Review by LinHuiqing — APPROVED** [review]
lgtm

**Pull request merged**
