### PR TITLE
Release 2021-10-26

### PR DESCRIPTION
**Pull request by LoneRifle**
This release contains the following major changes:
- #630 
  - #660 
  - #661 
- #611 
  - #652 
  - This change also contains a refactor to use neverthrow
- #651 
- #657

It also contains the following:
- #645

### CODE REVIEW

**Review by LinHuiqing — COMMENTED** [review]
#611, #652, #651 and #657 lgtm

**Comment by LoneRifle** [comment]
> #611, #652, #651 and #657 lgtm

could you approve then? =)

**Review by wanlingt — COMMENTED** [review]
found a bug with #630 :( not filtering by agencies on agency pages, taking a look now

**Review by wanlingt — APPROVED** [review]
search works now

**Pull request merged**
